feat: week1 필수 과제 구현
DO-SOPT-ANDROID/dongmin-park pull request #1
Opened 2023-10-09 14:57 UTC by chattymin

LoginActivity
- 회원가입 버튼 추가
- registerForActivityResult, putExtra 활용
- Toast 활용
- 비밀번호 안보이게 설정

SignUpActivity
- MBTI, About Me 추가
- 회원가입 제한조건 설정
- 회원가입성공 Toast 추가

MainActivity
- 로그인(회원가입)에서 받아온 정보 활용
- 이미지 constrainDimensionRatio 사용
- 적절한 간격 부여

용량이 커서 압축해서 올립니다 :)
[필수과제 시연영상](https://github.com/DO-SOPT-ANDROID/dongmin-park/files/12847543/SOPT_week1_necessary.webm.zip)

- Revert 기록은 심화과제도 한번에 올리는줄 알고 올렸다가 공지보고 후다닥 내렸습니다 ㅎㅎ

2023-10-09 16:13 UTC, memoryBangwool commented on app/src/main/java/org/sopt/dosopttemplate/SignUpActivity.kt
> +    private fun makeToast(text: String) {
makeToast 를 함수로 따로 분리한 게 깔끔해요!
(다른 함수들도 그렇고요)

2023-10-10 04:10 UTC, Marchbreeze reviewed
아좌잣 ~

2023-10-10 04:10 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/LoginActivity.kt
> +    private fun login() {
함수명이 더 직관적이었으면 합니다! login() 보다는 checkLoginAvailable() 과 같은 방식으로 수정하면 이후에 유지보수를 진행하는 과정에서 더 쉽게 코트를 알아볼 수 있어요 ~~

2023-10-10 04:10 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/LoginActivity.kt
> +        }
이러한 부분도 xml id를 더 직관적으로 설정하면 더 좋은 코드를 작성할 수 있어요! 
저는 보통 xml id를 [what_where_description] 형식으로 작성합니다. 
id: tv_login_title -> binding: tvLoginTitle
[안드로이드 네이밍 규칙](https://velog.io/@tlsgks48/%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-%EB%A6%AC%EC%86%8C%EC%8A%A4-%EB%84%A4%EC%9D%B4%EB%B0%8D-%EA%B7%9C%EC%B9%99)
을 참고하면 더 좋을 듯 합니닷

2023-10-10 04:10 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/MainActivity.kt
> +        binding.Nickname.text = intent.getStringExtra("NICKNAME")
닉네임 부분만 형식이 다른 이유가 있나요?

2023-10-10 04:10 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/SignUpActivity.kt
> +    private fun isMBTICorrect(text: String) = Regex("^[a-zA-Z]{4}\$").matches(text) // 영어 4글자
Regex 사용 좋네요 !

2023-10-10 04:10 UTC, Marchbreeze commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintDimensionRatio="1:1"
그냥 1만 써도 1:1 효과를 얻을 수 있답니닷 ~~~

2023-10-10 05:05 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/LoginActivity.kt
> +    private fun login() {
이 부분은 미처 생각하지 못했네요. 앞으로 함수명을 작성할때 참고하도록 하겠습니다. 감사합니다 !!!

2023-10-10 05:33 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/LoginActivity.kt
> +        }
어머머 저건 왜 저렇게 돼있지

깜빡하고 안바꾼거 같네요. 네이밍 규칙은 참고해서 더 좋은 코드로 수정해보겠습니다! 링크 공유 감사합니당

2023-10-10 05:35 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/MainActivity.kt
> +        binding.Nickname.text = intent.getStringExtra("NICKNAME")
ID, MBTI는 원래 대문자로 표기해야하니 대문자로 하고, nickname은 일반 명사기때문에 시작부분만 대문자로 했습니다.
getStringExtra에 넣는 것은 전부 대문자로 했구요.

근데 지금 보니까 Nickname에만 "text"가 빠져있고, 이것만 대소문자 섞인것 처럼 보이네요
한번 더 생각하고 네이밍 해야겠습니다.

2023-10-10 05:35 UTC, chattymin commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintDimensionRatio="1:1"
오오 꿀팁 감사합니다 👍

2023-10-10 05:47 UTC, KwakEuiJin reviewed
정규식 사용 너무 멋있습니다 👍 프로필은 더 멋있어요 고생하셨습니다~!!

2023-10-10 05:47 UTC, KwakEuiJin commented on app/src/main/AndroidManifest.xml
> +        </activity>
intent-filter가 정의되지 않은 액티비티의 경우 exported 가 false여도 됩니다 이유를 같이 찾아보시면 좋을 것 같아요~!!

2023-10-10 05:47 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/LoginActivity.kt
> +    }
1. [Kotlin 의 scope 함수](https://kotlinlang.org/docs/scope-functions.html)를 활용한다면 더욱 가독성 좋은 코드를 만들 수 있을 것 같습니다
2. 코[틀린에서 변수명은 주로 camelCase를 권장](https://kotlinlang.org/docs/coding-conventions.html#property-names)합니다, 대문자 선언은 상수 선언시 사용되요~!!

2023-10-10 05:47 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/SignUpActivity.kt
> +        else "ERROR\n다시 시도해주세요"
이렇게 분기 동작이 많은 경우 Kotlin의 when문을 사용해보시는 걸 추천드립니다~!!

2023-10-10 05:47 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/SignUpActivity.kt
> +    private fun isMBTICorrect(text: String) = Regex("^[a-zA-Z]{4}\$").matches(text) // 영어 4글자
정규식 적용 너무 멋있습니다! 다만 기존 MBTI 형식 외에 타입이 들어갈 수 있을 것 같네요! 이 부분은 어떻게 해결하는 것이 효율적일지 한번 더 고민해보시면 좋을 것 같습니다 (예시: ABCD -> isCorret = true)

2023-10-10 06:12 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/SignUpActivity.kt
> +        else "ERROR\n다시 시도해주세요"
kotlin의 when문을 제가 사용법을 하나만 알고있었네요!
아래와 같은 방식만 가능한 줄 알았는데 ()가 없는 when문이 있는건 처음 알았습니다.
적용해보겠습니다!!
when(){
}

2023-10-10 06:15 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/SignUpActivity.kt
> +    private fun isMBTICorrect(text: String) = Regex("^[a-zA-Z]{4}\$").matches(text) // 영어 4글자
기존 MBTI가 아닌 다른 값이 들어가는 부분도 정규표현식으로 거르는 생각을 했었지만, 일부러 재미를 위해 남겨뒀었습니다 ㅋㅋㅋ
저희 노션처럼 CUTE라거나, EEEE와 같은 재치있는 MBTI를 기대하고자 "영어4개"라는 조건만 생각했습니다. 

중요한 정보는 말씀하신 것 처럼 꼼꼼하게 검증하도록 하겠습니다 :)

2023-10-10 06:54 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/MainActivity.kt
> +        binding.Nickname.text = intent.getStringExtra("NICKNAME")
조아용 얼라인된 네이밍 필수 ~~~~

2023-10-10 13:17 UTC, chattymin commented on app/src/main/AndroidManifest.xml
> +        </activity>
공부해봤는데 자세히 들어가니 스토리가 아주 깊군요...
일단 exported가 false여도 되는 이유는 찾았습니다 ㅎㅎㅎ 감사합니다!
더 자세한 원리는 천천히 공부해보도록 하겠슴당

2023-10-10 13:19 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/LoginActivity.kt
> +    }
scope함수를 이번 기회에 공부해보도록 하겠습니다! 링크 공유까지 감사합니다 :)
혼자 개발하던게 습관이 돼서 아무래도 변수를 대충 작성하네요. 세미나 기간동안 고쳐나가보겠습니당 ㅎ

2023-10-10 18:57 UTC, stellar-halo requested changes
고생하셨습니다~

2023-10-10 18:57 UTC, stellar-halo commented on app/src/main/java/org/sopt/dosopttemplate/LoginActivity.kt
> +                    val AboutMe = result.data?.getStringExtra("ABOUTME") ?: ""
DataClass를 하나 만들어보는 건 어떨까요?

2023-10-10 18:57 UTC, stellar-halo commented on app/src/main/java/org/sopt/dosopttemplate/LoginActivity.kt
> +    }
이것처럼 반복되는 함수는 Util로 빼보시는 건 어떤가요?

2023-10-10 18:57 UTC, stellar-halo commented on app/src/main/res/layout/activity_login.xml
> +        android:id="@+id/textView2"
id에 숫자는 최대한 사용하지 않는 것이 좋습니다! 리팩토링하거나 팀원이 코드를 볼 때 알아보기 어려우니 조금 길더라도 자세하게 써주세요~

2023-10-10 18:57 UTC, stellar-halo commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintBottom_toBottomOf="@+id/Nickname"
@+는 생성입니다! 문제없이 빌드되기는 하지만,,, @id로 쓰시면 됩니다 ㅎㅎ

2023-10-10 18:57 UTC, stellar-halo commented on app/src/main/res/layout/activity_signup.xml
> +        android:text="비밀번호"
string으로 한 번 뺴봅시다!

2023-10-11 06:11 UTC, Marchbreeze commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintBottom_toBottomOf="@+id/Nickname"
섬세한 코드리뷰 미쳤다 어떻게 발견했지

2023-10-11 06:16 UTC, chattymin commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintBottom_toBottomOf="@+id/Nickname"
wow 몰랐던 사실이네요

전부 수정하겠슴당

2023-10-11 06:26 UTC, chattymin commented on app/src/main/res/layout/activity_login.xml
> +        android:id="@+id/textView2"
어머 저것도 저렇게 해뒀네

수정하겠습니다 :)

2023-10-11 14:55 UTC, lsakee reviewed
덩민이 잘하네유

2023-10-11 14:55 UTC, lsakee commented on app/src/main/AndroidManifest.xml
> +            android:exported="false"></activity>
꺽세닫아도 될거 같아유

2023-10-11 14:55 UTC, lsakee commented on app/src/main/java/org/sopt/dosopttemplate/LoginActivity.kt
> +    private fun isPWCorrect(PW: String) = PW == intentToMainActivity.getStringExtra("PW")
코틀린 스럽네여 ㅎㅎ

2023-10-11 14:55 UTC, lsakee commented on app/src/main/java/org/sopt/dosopttemplate/LoginActivity.kt
> +                    val AboutMe = result.data?.getStringExtra("ABOUTME") ?: ""
만들면서 Parcelable 도 적용해 보시면 좋을거 같소

2023-10-11 14:55 UTC, lsakee commented on app/src/main/java/org/sopt/dosopttemplate/MainActivity.kt
> +        binding.tvMainAboutMe.text = intent.getStringExtra("ABOUTME")
바인딩 쓰기 귀찮으면 with(binding) 써도 될듯

2023-10-11 14:55 UTC, lsakee commented on app/src/main/res/layout/activity_signup.xml
> +        android:text="회원가입 하기"
텍스트들 스트링으로 빼도 좋을듯 유

2023-10-11 19:53 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/LoginActivity.kt
> +                    val AboutMe = result.data?.getStringExtra("ABOUTME") ?: ""
다.... 구현했습니다...
밤새 정말 많은 일이 있었어요... 훌쩍 😢

2023-10-11 19:54 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/MainActivity.kt
> +        binding.tvMainAboutMe.text = intent.getStringExtra("ABOUTME")
with 문법 처음 알게됐는데 상당히 편하네요
꿀팁 냠냠 했슴다 :)

2023-10-11 19:55 UTC, chattymin commented on app/src/main/AndroidManifest.xml
> +            android:exported="false"></activity>
오호 xml이 익숙치 않아서 몰랐네요
감삼당

2023-10-11 19:58 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/LoginActivity.kt
> +    }
확실히 코드가 깔끔해졌네요
죠씁니다!!

2023-10-11 20:20 UTC, chattymin commented on app/src/main/res/layout/activity_signup.xml
> +        android:text="비밀번호"
xml에서는 String 분리하는게 권장사항이었네용
전부 분리 완료했습니다 ㅎㅎ

2023-10-11 20:20 UTC, chattymin commented on app/src/main/res/layout/activity_signup.xml
> +        android:text="회원가입 하기"
분리 완료 했어유

2023-10-13 08:12 UTC, crownjoe reviewed
많이 배워갑니다...👍 이번 주도 수고하셨어요!!

2023-10-13 08:12 UTC, crownjoe commented on app/src/main/java/org/sopt/dosopttemplate/LoginActivity.kt
> +        user = result.data?.getParcelable("USER", User::class.java) ?: return
Parcelable 쓰신 거 보고 저도 공부해갑니다!!

2023-10-13 08:12 UTC, crownjoe commented on app/src/main/java/org/sopt/dosopttemplate/LoginActivity.kt
> +                return@setOnClickListener
이렇게 간결하게 쓸 수 있군요!!!

2023-10-13 08:12 UTC, crownjoe commented on app/src/main/java/org/sopt/dosopttemplate/Model/User.kt
> +): Parcelable
이렇게 데이터 클래스를 정의하는군요..! 한 수 배워갑니다...👍👍

2023-10-16 14:50 UTC, lsakee approved these changes
LGTM 계속계속 고친 티가 나네요 멋집니다 ㅎㅎ

2023-10-16 15:13 UTC, stellar-halo approved these changes
동민님. 당신의 배움에 대한 열정 따봉 박고갑니다👍

2023-10-16 15:37 UTC, merged