Feat/week6 essential
DO-SOPT-ANDROID/dongmin-park pull request #13
Opened 2023-12-05 01:15 UTC by chattymin

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #12

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- Issue 참고
- MVVM 설계
- 코루틴 적용

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/DO-SOPT-ANDROID/dongmin-park/assets/52882799/e1d439a7-c181-48e6-8cf6-56425fb893e1

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
DataBinding이랑 MVVM을 한번 적용해봤습니다!
제대로 적용했는지 아직은 좀 헷갈리네용...
처음 적용해봐서 잘 했는지 모르겠는데 더 좋은방법 있다면 코리 부탁드려용 ㅎㅎ

2023-12-05 08:04 UTC, lsakee requested changes
그만 잘해 박동민

2023-12-05 08:04 UTC, lsakee commented on app/src/main/java/org/sopt/dosopttemplate/data/repository/UserRepository.kt
> +            userService.getUserList(page).data
데이터소스를 공부해보고 레포지토리 패턴한번 알아보시기 바랍니다!

2023-12-05 08:04 UTC, lsakee commented on app/src/main/java/org/sopt/dosopttemplate/presentation/login/LoginViewModelFactory.kt
> +class LoginViewModelFactory : ViewModelProvider.Factory {
뷰모델 팩토리를 한군대서 해줘도 될듯합니다 ㅎ

2023-12-05 17:31 UTC, Marchbreeze reviewed
코드 맛있네요 이집 ~

2023-12-05 17:31 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/data/service/AuthService.kt
> +    suspend fun login(
정말 사소한거긴한데, 저는 서비스에서처럼 서버통신 관련 함수들의 네이밍을 postxxx(), getxxx() 처럼 서버통신의 종류를 명확하게 가져가주는게 안헷갈리더라구요! 물론 네이밍은 취향 차이~

2023-12-05 17:31 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/user/UserFragment.kt
> +    }
adapter도 _binding처럼 따로 백패킹해준 후, 생명주기가 마무리될 때 null 처리해주면서 메모리 누수를 방지해주도록 설계해둘 수 있어요! 화면과 관련된 연결들은 화면 생명주기에 따라서 좌우되는 방법이 더 권장되니, 한번 찾아보면 좋을 듯 합니당 ~

2023-12-05 17:31 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/presentation/login/LoginActivity.kt
> +        }
이 방법도 물론 좋지만, <뷰모델에서 id 수정 -> 액티비티에서 감지 -> 뷰모델에서 id 체크 -> 액티비티에서 UI에 표시될 값 변경> 의 로직보다는 뷰모델에서 아예 idValid의 값을 액티비티에서 감지하는 방법이 효과적일 것 같아요!

2023-12-06 04:00 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/presentation/login/LoginActivity.kt
> +        }
음 그렇네요! 말씀해주신거 보고 다시 제 코드를 보니까 너무 비효율적인거 같네용... 말해주신 내용으로 수정하겠습니다!!
감사합니당 😁

---
단순히 변수만 늘리니까 기존과 큰 차이는 없는데 변수만 늘어난 것 같더라구요
그래서 버튼 검사 로직도 손보니까 이게 더 효율적으로 바뀐 것 같습니다!
기존에 비해서 검사 횟수도 더욱 효율적으로 줄었어요 :)

2023-12-06 04:00 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/user/UserFragment.kt
> +    }
이 부분은 몰랐네요! 공부해보고 적용하도록 하겠습니다 :)

2023-12-06 04:02 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/data/repository/UserRepository.kt
> +            userService.getUserList(page).data
매번 새로운 공부 할 정보 주셔서 감사합니다!!
덕분에 매주 성장하고있어요 ✌️

2023-12-06 04:06 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/presentation/login/LoginViewModelFactory.kt
> +class LoginViewModelFactory : ViewModelProvider.Factory {
변경하도록 하겠습니다!!
그런데 하나의 viewModelFactory로 합치니 내부에서 when문으로 검사 후 각각 repository를 주는 방식으로 됐는데 이게 맞는 방식일까요...?

2023-12-08 15:07 UTC, stellar-halo approved these changes
컴포즈맨,,에 이어 xml도 씹어먹으려는가,, 깔끔하고 군더더기 없는 코드 잘 보고 갑니다!

2023-12-08 15:07 UTC, stellar-halo commented on app/build.gradle
> +        dataBinding true
데바의 세계로,,

2023-12-08 15:07 UTC, stellar-halo commented on app/src/main/java/org/sopt/dosopttemplate/presentation/signup/SignUpViewModel.kt
> +    }
저도 아직 안써봤는데,,!!! 공부해오겠습니다

2023-12-08 15:07 UTC, stellar-halo commented on app/src/main/java/org/sopt/dosopttemplate/presentation/login/LoginActivity.kt
> +        loginViewModel.pw.value = pw
여기서 직접 viewModel에 접근하는 것보다는 viewModel 내부에서 값을 바꿔주는 것은 어떨까요?

2023-12-10 11:03 UTC, memoryBangwool commented
동민이형,,, 빛난다...

2023-12-10 11:29 UTC, lsakee reviewed
고생하셨습니다

2023-12-10 11:29 UTC, lsakee commented on app/src/main/java/org/sopt/dosopttemplate/presentation/signup/SignUpActivity.kt
> +                }
error도 데바를 활용하면 xml로 이전도 가능 할 듯합니다 모르셨다면 참고

2023-12-10 13:31 UTC, crownjoe reviewed
오늘도 배워갑니다 따봉 😎👍👍 이번 주도 수고하셨슴니다!!

2023-12-10 13:31 UTC, crownjoe commented on app/src/main/java/org/sopt/dosopttemplate/data/repository/LoginRepository.kt
> +        }
렛츠고 코루틴...😎😎

2023-12-10 13:31 UTC, crownjoe commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/user/UserViewModel.kt
> +        }
요렇게 livedata 이용하는 거군요 오늘도 배워갑니다!!!

2023-12-10 13:31 UTC, crownjoe commented on app/src/main/java/org/sopt/dosopttemplate/presentation/signup/SignUpViewModel.kt
> +        val PW_REGEX: Pattern = Pattern.compile(pwRegex)
이렇게 깔끔하게 검사할 수 있군요!!

2023-12-11 04:01 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/presentation/login/LoginActivity.kt
> +        loginViewModel.pw.value = pw
그렇게 하는게 훨씬 더 viewModel을 올바르게 활용하는 방법 같네요!!!
생각 못하던 부분인데 감사합니다! 덕분에 한번 더 관심사 분리를 신경써서 코드 수정해보겠습니다!

2023-12-11 07:31 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/presentation/signup/SignUpActivity.kt
> +                }
아....!! 헐 대박!

당장 적용합죠

2023-12-11 07:32 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/presentation/signup/SignUpViewModel.kt
> +    }
수정하다보니 날려버리긴 했는데 그래도 좋은 기능 같아용 ㅎㅎㅎ

2023-12-11 07:43 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/presentation/login/LoginActivity.kt
> +        }
이부분은 코드를 날려버렸습니다!! State로 관리하는게 훨씬 좋아보이더라구용
그리고 error를 설정하는 부분을 xml파일로 이동시켜서 데이터 바인딩을 더욱 활용하였습니다 :)

덕분에 수정 방향성을 정할 수 있었네요 ㅎㅎㅎ

2023-12-28 17:35 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/data/repository/UserRepository.kt
> +            userService.getUserList(page).data
7주차에 통합해서 적용해뒀습니다!! 확인하고 어프루브 부탁드립니당 ㅎㅎ....

2023-12-28 17:35 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/presentation/login/LoginViewModelFactory.kt
> +class LoginViewModelFactory : ViewModelProvider.Factory {
힐트로 슉삭 해서 뷰모델 팩토리 없애버림~ 예~~~

2024-02-02 11:11 UTC, merged