Feat/week1 deep 심화과제 제출
DO-SOPT-ANDROID/dongmin-park pull request #2
Opened 2023-10-12 14:51 UTC by chattymin

- [ ] Activity 생명주기 -> 작성중
- [x] inputType 속성으로 editText 줄 제한 & 엔터키 활용
- [x]  windowSoftInputMode 속성으로 키보드가 올라갈 때 화면도 같이 올라가기
- [x]  hideKeyboard() 함수로 키보드 숨기기
- [x] hideKeyboard() 함수로 키보드 숨기면서 커서 포커스 제거

[week1 심화과제 시연영상.webm](https://github.com/DO-SOPT-ANDROID/dongmin-park/assets/52882799/47211b68-b430-4518-aa0b-770145959674)

2023-10-17 02:28 UTC, librarywon reviewed
캬 갓동민 너무 멋진 코드 잘 보고 갑니다!

2023-10-17 02:28 UTC, librarywon commented on app/src/main/java/org/sopt/dosopttemplate/LoginActivity.kt
> +        intentToMainActivity.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK or Intent.FLAG_ACTIVITY_NEW_TASK)
아래는 인텐트 스코프를 적용하였는데 여기도 적용해보는게 어떨까요?

2023-10-17 02:28 UTC, librarywon commented on app/src/main/java/org/sopt/dosopttemplate/LoginActivity.kt
> +        private const val DEFAULT_ERROR = "ERROR\n다시 시도해주세요"
직접 텍스트를 적는 하드코딩은 지양하는 것이 좋을 것 같습니다 스트링 파일에서 관리해볼까요?

2023-10-17 02:28 UTC, librarywon commented on app/src/main/java/org/sopt/dosopttemplate/util/GetParcelable.kt
> +fun <T> Intent.getParcelable(name: String, clazz: Class<T>): T? {
인탠트 관련 확장함수가 늘어날 것을 대비해서 파일 이름을 IntentExt 같은 범용적인 이름으로 하시는 건 어떠신가요

2023-10-17 02:28 UTC, librarywon commented on app/src/main/java/org/sopt/dosopttemplate/SignUpActivity.kt
> +        }
when을 활용해서 상황에 따라 다른 텍스트가 나오게 하는 방법 너무 좋은 것 같아요

2023-10-17 06:35 UTC, taeheeL approved these changes
굳굳

2023-10-17 06:35 UTC, taeheeL commented on app/src/main/java/org/sopt/dosopttemplate/LoginActivity.kt
> +        binding.etvLoginPw.setText(user?.pw)
텍스트 set 작업을 코틀린의  프로퍼티 접근 구문(property access syntax)을 사용하여 
```suggestion
        binding.etvLoginId.text = user?.id
        binding.etvLoginPw.text = user?.pw
```
이렇게 바꿀 수 있습니다. 좀 더 코틀린스럽게, 간결하고 직관적이고 가독성 좋게 바꾸는 방법이지요, 아마 안스에서 위와 같이 바꾸라고 제안을 하고 있을 겁니다 :)

2023-10-17 06:35 UTC, taeheeL commented on app/src/main/java/org/sopt/dosopttemplate/SignUpActivity.kt
> +    private fun isPWCorrect(len: Int) = len in 8..12
코틀린스럽다

2023-10-17 06:47 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/LoginActivity.kt
> +        private const val DEFAULT_ERROR = "ERROR\n다시 시도해주세요"
string 리소스에서는 xml파일에 들어가는 string만 처리하고 kotlin파일에서 쓰이는 String 값은 따로 빼서 관리하는줄 알았었습니다!! 덕분에 합쳐도 된다는걸 알게 됐네요!

그런데 궁금한 부분이 하나 생겼습니다. string 파일에서 많은 값들을 저장하고 있는데 하나의 파일에 너무 많은 string이 들어가게 된다면 오히려 가독성이라거나, 추후 관리하는데 더 어려울 것 같습니다. 이렇게 되면 파일을 분리해서 저장하게 되나요??

2023-10-17 07:14 UTC, librarywon commented on app/src/main/java/org/sopt/dosopttemplate/LoginActivity.kt
> +        private const val DEFAULT_ERROR = "ERROR\n다시 시도해주세요"
아직 string file들을 분리해서 사용해본 적이 없어서 말씀을 어떻게 해봤다고는 말씀드리지 못하지만 실제로 서버를 붙이게 되면 상당수의 값들을 서버에서 받아오게 되서 굳이 분리까지 하지 않아도 된다고 생각합니다.
실제로 제가 개발하고 있는 서비스인 '포포리'에서도 string 파일의 코드가 60줄이 넘지 않습니다.

그리고 유지 보수 측면에서도 string 파일 안에서 모든 텍스트 파일을 관리하는 것이 좋다고 생각합니다. 로직이 들어있는 파일도 아니고 상수값만 들어 있으니까요!

2023-10-17 08:24 UTC, librarywon commented on app/src/main/java/org/sopt/dosopttemplate/SignUpActivity.kt
> +    private fun isPWCorrect(len: Int) = len in 8..12
그 스터디가 생각나네요

2023-10-17 09:07 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/LoginActivity.kt
> +        private const val DEFAULT_ERROR = "ERROR\n다시 시도해주세요"
아하 감사합니다 :)
앞으로 코드 작성하는데 반영해서 좋은 코드 잘 짜보겠습니다 ㅎㅎ

2023-10-17 09:08 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/util/GetParcelable.kt
> +fun <T> Intent.getParcelable(name: String, clazz: Class<T>): T? {
관련 확장을 고려하지 않고 작성했네요!! 반영하도록 하겠습니다. 감사합니다~👍

2023-10-17 09:18 UTC, taeheeL commented on app/src/main/java/org/sopt/dosopttemplate/LoginActivity.kt
> +        binding.etvLoginPw.setText(user?.pw)
EditText인줄 몰랐네요 코드리뷰 취소!

2023-10-17 09:39 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/LoginActivity.kt
> +        intentToMainActivity.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK or Intent.FLAG_ACTIVITY_NEW_TASK)
깔끔하게 적용 완료했습니다!!!
덕분에 코드가 한결 깔끔해졌네요 :)

2023-10-18 16:16 UTC, lsakee requested changes
열심히하는 모습 좋네요

2023-10-18 16:16 UTC, lsakee commented on app/src/main/java/org/sopt/dosopttemplate/SignUpActivity.kt
> +    }
Sign in에 있는 코드랑 똑같은데 재사용 할 수 있는 방법이 없을까요?

2023-10-18 16:16 UTC, lsakee commented on app/src/main/java/org/sopt/dosopttemplate/LoginActivity.kt
> +            finish()
피니시 쓴 이유 있나요?

2023-10-19 10:26 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/SignUpActivity.kt
> +    }
util로 빼서 재사용 하려다가 baseActivity속으로 넣어버렸습니다.

근데 이렇게 짜다보면 baseActivity가 더러워질것만 같은 느낌이 들긴 하네요
그런데 또 안넣기엔 어차피 매번 함수 호출을 해줘야하고... 코드 반복같고... 뭐가 좋은지 모루겠소요...

공부 좀더 해보겠습니당

2023-10-19 10:37 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/LoginActivity.kt
> +            finish()
현재 진행중인 액티비티를 종료하겠다는 의미로 썼는데 지금 생각해보니까 저기 들어있어야 하는게 아니라 밖에 있어야 하네요

함수는 하나의 기능만 하는게 좋은데 제가 만든 함수는 이동, 토스트생성, 액티비티 종료 까지 총 3개의 역할을 하고있네요
그래서 로그인 성공시 저 세가지를 모두 실행시키는 함수를 만들고, 기존 함수는 이동과 관련된 정보만 담도록 수정했습니다!!
덕분에 많은걸 깨달았네요 :)

2023-10-19 11:13 UTC, lsakee approved these changes
한주동안도 엄청 성장하셨군요 이제 시험 공부하세요 !!

2023-10-19 11:56 UTC, merged