Feat/week2 essential
DO-SOPT-ANDROID/dongmin-park pull request #5
Opened 2023-10-24 15:36 UTC by chattymin

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #4 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- homeFragment부터 시작
- 마이페이지 적용
- 내 프로필 구현
- 멜론뮤직 구현
- Sealed Class 적용
- 생일 구현 

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/DO-SOPT-ANDROID/dongmin-park/assets/52882799/3c37d1b0-0b59-4a31-849f-073494013f42

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴

생일인 사람과, 생일이 아닌 사람의 경우 큰 ui 차이가 없는데 굳이 구분할 필요가 있나용??
Date값 변수를 활용해서 birthday인지 확인하고 해도 될거 같은데 구분하는게 더 좋은 방법인가용

BaseFragment의 getFragmentBinding 함수를 없애버릴 수 있을까요...?
BaseActivity처럼 매개변수를 받아와서 내부에서 처리하고싶은데 코드 반복이 생기는게 맘에 좀 걸리네용

폴더 정리...어케할지 모루겠소요

2023-10-25 16:46 UTC, KwakEuiJin reviewed
컴포즈도 보고싶어요!!!

2023-10-25 16:46 UTC, kez-lab commented on app/src/main/java/org/sopt/dosopttemplate/HumanAdapter.kt
> +
var, mutableList를 같이 쓰게되면 가변 + 가변 구조가 됩니다, val mutableList로 add를 하거나 var List로 list의 객체 변경을 하는 구조로 변경하면 좋을 것 같습니다!!

2023-10-25 16:46 UTC, kez-lab commented on app/src/main/java/org/sopt/dosopttemplate/FriendViewHolder.kt
> +    }
isVisible이라는 것도 있으니 참고해보시면 좋을 것 같습니다!

2023-10-25 16:46 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/home/HomeActivity.kt
> +    }
getUserInfo() 를 throw exception을 했으면 사용 구문에서 try catch 로 묶어서 핸들링하셔야 안전한 개발이 가능합니다!!

2023-10-25 17:15 UTC, kangyuri1114 reviewed
^^b

2023-10-25 17:15 UTC, kanghwayuri commented on app/src/main/java/org/sopt/dosopttemplate/home/HomeViewModel.kt
> +            name = "강유리",
나 리뷰어가 왜 됐지 .. 하믄서 들어왔는ㄷㅔ 따봉 드립니다 ^^b

2023-10-25 17:15 UTC, kangyuri1114 commented on app/src/main/java/org/sopt/dosopttemplate/MyViewHolder.kt
> +        binding.tvSelfDecription.text = friendData.aboutMe
스코프함수 추천드립니다 ^^b 저도 처음 써봤는데 좋드라구여

2023-10-25 17:15 UTC, kanghwayuri commented on app/src/main/java/org/sopt/dosopttemplate/base/BaseFragment.kt
> +abstract class BaseFragment<T : ViewBinding> : Fragment() {
저는 base 를 한번도 안써봤는데 base 액티비티, 프래그먼트를 쓰는 이유를 알 수 있을까용? 오비분들도 많이 만들어두셨던데..

2023-10-26 02:46 UTC, Jokwanhee reviewed
박동민.. 키도 크고 잘생겼는데 코드까지 완벽하네요; 잘 보고 갑니다 🌺

2023-10-26 02:46 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/home/HomeViewModel.kt
> +            aboutMe = "생일선물은 프로틴으로 받겠습니다",
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 누가보면 프로틴 괴물인줄.. 하지만 감사합니다 😄

2023-10-26 02:46 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/base/BaseFragment.kt
> +    abstract fun getFragmentBinding(inflater: LayoutInflater, container: ViewGroup?): T
저도 액티비티와 달리 프래그먼트의 Base 추상 클래스를 작성하면서, 액티비티 처럼 깔끔하게 onCreateView 내부에서 작성되지 않고 또 구현할 수 있는 함수를 만들어야 하더라구요! 그래서 저는 DataBinding 을 사용했지만! 나쁘지 않은 것 같아요! DataBinding 에서는 DataBindingUtil 클래스를 제공해서 View를 인플레이트 할 수 있어서 해당 함수를 작성하지 않아도 되었어요! 
```kotlin
abstract class BaseFragment<T: ViewDataBinding> : Fragment() {
...
   override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        _binding = DataBindingUtil.inflate(inflater, layoutId, container, false)
        return binding.root
    }
    ...
}
```

2023-10-26 03:30 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/HumanAdapter.kt
> +
헉 이건 제 실수네용... 
평소 mutableList 쓸때 val로 썼었는데 왜저랬징.... 감삼다!

2023-10-26 03:31 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/FriendViewHolder.kt
> +    }
오호 그런것도 있군요!
이번에 xml을 처음 다뤄봐서 모르는게 많은데 덕분에 많이 배워갑니다 ㅎㅎ

2023-10-26 03:46 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/MyViewHolder.kt
> +        binding.tvSelfDecription.text = friendData.aboutMe
헉 이건 저번주때도 받은 지적이라 알고있었는데 습관이 무섭네요 허허...
다시 고치겠습니다 ㅎ

2023-10-26 03:57 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/base/BaseFragment.kt
> +    abstract fun getFragmentBinding(inflater: LayoutInflater, container: ViewGroup?): T
오오 조언 감사합니다!!
ViewBinding도 처음 배우는 입장이라 DataBinding은 멀리있는것처럼 느껴지는데 대단하시네요 ㅎㅎㅎ
저도 열심히 해보겠슴😤

2023-10-26 04:01 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/base/BaseFragment.kt
> +abstract class BaseFragment<T : ViewBinding> : Fragment() {
base를 쓰게 되면 간단하게 말해서 코드 중복을 줄일 수 있습니다!!
예를 들어 제가 이번에 구현한 BaseFragment를 보시면 onCreateView라거나, onDestroyView의 경우 모든 Fragment에 들어가는 공통 함수입니다.
어머 onDestryView 순서 바꼈네 수정해야겠따ㅎㅎ

여튼 모든 Fragment나 Activity에 들어가는 공통 내용을 Base에 넣고, 그 Base를 상속받아 사용한다면 코드 중복을 줄일 수 있겠죠!!

2023-10-26 05:42 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/home/HomeActivity.kt
> +    }
이 부분은 미처 생각하지 못했네요!!
try catch로 묶어서 에러가 발생할 경우 user 정보가 제대로 받아지지 않았다는 것이기 때문에 에러 메시지와 함께 LoginActivity로 쫓아냈습니다 ㅎㅎ

원래 use id와 pw가 맞을 경우 toast를 띄우면서 로그인 성공이라고 했는데, 위 방법으로 바꾸니까 로그인성공 토스트가 떴는데 로그인 스크린이길래 이 함수 내에 성공/실패여부에 따라 다른 toast를 띄우도록 수정했습니당

이 함수가 하는 역할이 많아져서 조금 더 분리를 진행했고, setUser라는 함수로 이런저런 절차를 다 하게 했습니다. 근데 toast 텍스트도 정해주고, 토스트도 띄우고, 유효성검증역할도 하는데 setUser라는 함수명이 맞을까요...? 아닌거 같은데 대안을 모루겟소요....😢

2023-10-26 14:38 UTC, taeheeL commented on app/src/main/java/org/sopt/dosopttemplate/base/BaseFragment.kt
> +abstract class BaseFragment<T : ViewBinding> : Fragment() {
과연 Base가 항상 정답일까요? [몬스터](https://proandroiddev.com/baseactivity-and-basefragment-are-monsters-5cda31639938)가 될 수도 있습니다..

한번 읽어보시고 Base를 무작정 따라 하는 게 좋은 선택인지? 생각해보시면 좋을 것 같네요 ㅎㅎ 
진짜진짜 쓰지 말라는거는 아닙니다.. 부장님 컨셉 잡혀서;;

2023-10-26 14:47 UTC, lsakee requested changes
그만잘해 동민 ..

2023-10-26 14:47 UTC, lsakee commented on app/src/main/java/org/sopt/dosopttemplate/HumanAdapter.kt
> +        notifyDataSetChanged()
이 코드가 뭔지 아시나욥? 밑줄 쳐져있지 않나요? diffutil 이란 키워드를 적용해보셔도 좋을거 같습니다 !

2023-10-26 14:47 UTC, lsakee commented on app/src/main/java/org/sopt/dosopttemplate/home/HomeActivity.kt
> +                        MyPageFragment.newInstance(
굿

2023-10-26 14:47 UTC, lsakee commented on app/src/main/java/org/sopt/dosopttemplate/home/HomeActivity.kt
> +            intent.getParcelable("USER", User::class.java) ?: throw IllegalArgumentException(
요부분은 에러를 던지기만 하나요?

2023-10-26 14:47 UTC, lsakee commented on app/src/main/java/org/sopt/dosopttemplate/home/HomeViewModel.kt
> +            aboutMe = "에그드랍 미만 잡",
에그드랍 사줄게 동민

2023-10-26 14:47 UTC, lsakee commented on app/src/main/java/org/sopt/dosopttemplate/model/HumanModel.kt
> +        @DrawableRes
디테일하네요!

2023-10-27 03:42 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/home/HomeActivity.kt
> +            intent.getParcelable("USER", User::class.java) ?: throw IllegalArgumentException(
getUserInfo에서 에러를 던지면, 이 함수를 호출하는 setUser에서 에러를 핸들링 하도록 했습니다!
처음에는 getUserInfo에서 에러처리까지 하게 할까 하다가 부수적으로 연결해야 할 것들이 많다고 생각해 에러를 던지는 함수와, 받은 에러를 처리하는 함수를 나눴습니다! 더 좋은 방법이 있다면 말씀해주시면 감사하겠습니다 :)

2023-10-27 04:14 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/base/BaseFragment.kt
> +abstract class BaseFragment<T : ViewBinding> : Fragment() {
저도 이부분은 상당히 경계하고있었는데 정리된 글을 보니까 한층 생각 정리에 도움이 됐네요!!

첫주차때 BaseActivity를 만들면서 "이정도까지나 Base에 넣어도 될까? 모든 Activity에서 사용하는게 아닌데?"라는 생각을 하면서 일단은 넣었습니다. 하지만, 해당 글을 보고나니 다른 방향으로 분리해보는게 좋을 것 같다는 생각이 드네요 :)

여윽시...부장님...덕분에...한 수...배워갑니다...^^7

2023-10-27 04:21 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/home/HomeViewModel.kt
> +            aboutMe = "에그드랍 미만 잡",
아싸 🥳

2023-10-27 17:38 UTC, Marchbreeze reviewed
아주~~~~~~~좋아요~~~~~~~~~~

2023-10-27 17:38 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/FriendBirthdayViewHolder.kt
> +            ivProfile.setImageResource(friendData.profileImage)
Coil 라이브러리로 이미지를 불러오면 더 성능이 좋아진답니다 ~~

2023-10-27 17:38 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/FriendViewHolder.kt
> +                ivItemFriendUseMelon.isVisible = true
```suggestion
            ivItemFriendUseMelon.isVisible = friendData.useMelon
```
처럼 표시할수도 있겠죠?

2023-10-27 17:38 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/home/HomeActivity.kt
> +            text = e.message!!
!! 사용은 앱이 터지는 요소가 될 수 있기 때문에 지양합시다 !! 대신 엘리스 연산자 ?: 를 활용해서 예외처리를 진행해보아요

2023-10-27 17:38 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/home/HomeActivity.kt
> +        }
인텐트 플래그 사용 야무지네요 ~~~~

2023-10-27 17:38 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/home/HomeViewModel.kt
> +            useMelon = false
아좌잣 !

2023-10-27 17:38 UTC, Marchbreeze commented on app/src/main/res/layout/fragment_home.xml
> +        android:layout_height="match_parent"
match_parent 사용을 지양합시다 ~~~~ 0dp와 Constraint를 활용해보아요

2023-10-27 17:38 UTC, Marchbreeze commented on app/src/main/res/layout/item_birthday_friend.xml
> +        android:text="chattymin"
이렇게 item의 UI를 만들때 예시로 텍스트 넣어보는 경우, tools:text 를 활용합시다 ~~

2023-10-28 06:18 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/home/HomeActivity.kt
> +            text = e.message!!
.toString()을 사용하는 방법으로 수정했습니다!

2023-10-28 06:18 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/FriendViewHolder.kt
> +                ivItemFriendUseMelon.isVisible = true
미쳐따...
안드로이드도 배우고 클린코드도 배워갑니다 ㄷㄷ

2023-10-29 05:50 UTC, chattymin commented on app/src/main/res/layout/fragment_home.xml
> +        android:layout_height="match_parent"
match_parent의 위험성을 몰랐네요! 덕분에 알게됐습니다. 감사합니다!!

2023-10-29 05:52 UTC, chattymin commented on app/src/main/res/layout/item_birthday_friend.xml
> +        android:text="chattymin"
Wowowowowowow 그저 갓상호...
이런게 있는지도 몰랐네요 👍

2023-10-29 06:42 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/FriendBirthdayViewHolder.kt
> +            ivProfile.setImageResource(friendData.profileImage)
바로 적용완료. Error와 Placeholder까지 야무지게 해버렸습니다. 키키

2023-10-29 06:42 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/HumanAdapter.kt
> +        notifyDataSetChanged()
행님... 이거 심화 과제더라구요 ㅎㅎ
심화 브랜치 새로 파서 작업하도록 하겠습니다!! :-)

2023-10-29 06:51 UTC, lsakee commented on app/src/main/java/org/sopt/dosopttemplate/HumanAdapter.kt
> +        notifyDataSetChanged()
ㅋㅋ 심화인줄 몰랐넹 할 수 있다 동민

2023-10-29 09:28 UTC, stellar-halo reviewed
고생하셨습니다! 엄청난,,성장 속도

2023-10-29 09:28 UTC, stellar-halo commented on app/src/main/java/org/sopt/dosopttemplate/model/HumanModel.kt
> +    ) : HumanModel()
왜 dataclass를 따로 만들었나요?
bod 속성이 하나 있으면 두 개의 데이터 클래스로 처리하지 않아도 될 것 같아요

2023-10-29 09:28 UTC, stellar-halo commented on app/src/main/res/layout/item_birthday_friend.xml
> +        android:id="@+id/iv_profile"
아래는 전부 iv_item인데 여기는 iv네요!

2023-10-29 09:28 UTC, stellar-halo commented on app/src/main/res/layout/item_birthday_friend.xml
> +        android:id="@+id/tv_name"
여기도 마찬가지입니다.

2023-10-29 09:28 UTC, stellar-halo commented on app/src/main/res/menu/menu_home.xml
> +        android:title="DO ANDROID" />
String,,,string,,,

2023-10-29 10:05 UTC, crownjoe reviewed
코드가 깔끔하고 배워가는 것이 참 많은 것 같슴니다 이번 주도 수고하셨어요!!!!

2023-10-29 10:05 UTC, crownjoe commented on app/src/main/java/org/sopt/dosopttemplate/FriendViewHolder.kt
> +                error(R.drawable.img_error)
이미지 로드 중에 오류가 발생했을 때 에러 이미지 띄우는 거 너무 좋은 것 같슴다 이런 것 하나하나 배워갑니당...!bb

2023-10-29 10:05 UTC, crownjoe commented on app/src/main/java/org/sopt/dosopttemplate/MyPageFragment.kt
> +                arguments = args
@JvmStatic을 이렇게 사용하는 거구나..!!!! 조장님이 이거 관련해서 코리 달아주셨는데 저도 이거에 대해 더 공부해볼게요!

2023-10-29 10:05 UTC, crownjoe commented on app/src/main/java/org/sopt/dosopttemplate/home/HomeActivity.kt
> +    }
이렇게 쓰니까 코드가 너무 깔끔...하네요 진심 한수 아니고 1000수 배워갑니닷!!

2023-10-29 10:05 UTC, crownjoe commented on app/src/main/java/org/sopt/dosopttemplate/home/HomeViewModel.kt
> +            aboutMe = "솔직히 숙대에서 내가 제일 코딩 잘한다 ㅋㅋ",
전 모르는 일...입니다 허허...

2023-10-29 11:47 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/model/HumanModel.kt
> +    ) : HumanModel()
그부분은 저도 생각했는데 과제에서 생일인 사람은 다른 ViewType으로 보이게 하라고 해서 새로 만들었습니다.
저도 body에 속성하나를 추가하고 하나로 처리하는게 더 좋다고 생각해용

2023-10-29 11:54 UTC, chattymin commented on app/src/main/res/layout/item_birthday_friend.xml
> +        android:id="@+id/iv_profile"
어머 xml 이름 참 대충지었네요.
실수 다 고쳤습니다!!

2023-10-29 11:57 UTC, chattymin commented on app/src/main/res/menu/menu_home.xml
> +        android:title="DO ANDROID" />
죄...죄송합니다...!!!

2023-11-09 13:35 UTC, lsakee approved these changes
LGTM 끊임없이 발전하는 모습 보기 좋네유

2023-11-09 13:35 UTC, lsakee commented on app/build.gradle
> +    implementation("io.coil-kt:coil:2.4.0")
dsl 문법이 석여있는데 통일성있는게 좋아보야영

2023-11-09 14:41 UTC, merged